include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - test/**.mocks.dart
    - lib/generated_plugin_registrant.dart
  strong-mode:
    implicit-casts: false
  errors:
    missing_required_param: error
    missing_return: warning
    unrelated_type_equality_checks: error
    # todo: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_escaping_inner_quotes
    - avoid_positional_boolean_parameters
    - parameter_assignments
    - prefer_null_aware_method_calls
    - require_trailing_commas
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_to_and_as_if_applicable
    - prefer_relative_imports
    - avoid_unused_constructor_parameters
    - sort_child_properties_last
    - directives_ordering