name: ygo_collection_manager
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  dynamic_theme:
    git:
      url: https://github.com/TesteurManiak/dynamic_theme.git
      ref: "2.0.0"
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  go_router: ^3.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  rxdart: ^0.27.3
  snapping_sheet: ^3.1.0

dev_dependencies:
  alchemist: ^0.2.1
  build_runner: ^2.1.7
  device_sizes:
    git:
      url: https://github.com/matthew-carroll/device_sizes.git
      ref: main
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  http_mock_adapter: ^0.3.2
  mockito: ^5.0.17
  remove_from_coverage: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/level/
    - assets/type/
    - assets/race/
    - assets/attribute/
  # Used for readable platform golden tests.
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
