// Mocks generated by Mockito 5.0.16 from annotations
// in ygo_collection_manager/test/data/datasources/remote/ygopro_remote_datasource_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ygo_collection_manager/data/api/api.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [RemoteClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteClient extends _i1.Mock implements _i2.RemoteClient {
  MockRemoteClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> get(String? uri) =>
      (super.noSuchMethod(Invocation.method(#get, [uri]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  String toString() => super.toString();
}
