name: Flutter

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '2.5.0'
    - run: flutter pub get
    - run: flutter format --set-exit-if-changed .
    - name: Analyze project source
      run: flutter analyze
      working-directory: ./lib
    - name: Test
      run: flutter test --coverage
    - name: Collect and report coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
