name: Flutter Web Build

on:
  push:
    branches:
      - 'web/**'

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '2.8.1'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web
